spring.application.name=SampleProject
spring.datasource.url=jdbc:postgresql://localhost:5432/fullstack_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.security.oauth2.client.registration.google.client-id=114831293192-4djga9l5dd1plmgomdr5f8t1g9qg94d3.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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